### ISSUE TITLE
license text and copyright?

### ISSUE THREAD

**Issue by pombredanne** [tmm1/rblineprof#28]
@tmm1 I reckon this fine code is MIT-licensed, but there is no text nor copyright I can find in the codebase proper... It would make it easier if you had that in the code IMHO.
Thanks!

**Comment by tmm1** [comment]
It says so here https://github.com/tmm1/rblineprof/blob/master/rblineprof.gemspec#L15

I will merge a PR that makes this more obvious by adding a LICENSE file.

**Comment by pombredanne** [comment]
@tmm1 perfect :+1:  Thank you my lord!
